CREATE TABLE CUSTOMER(
CUST_NAME VARCHAR(30),
CUST_EMAIL VARCHAR(30),
PHONE_NO VARCHAR(12) NOT NULL,
TOT_PURCHASE FLOAT NOT NULL,
CONSTRAINT CUST_EMAIL_PK PRIMARY KEY (CUST_EMAIL));

CREATE TABLE ACTOR(
A_ID VARCHAR(15),
ACT_NAME VARCHAR(30),
BIRTH_DATE DATE NOT NULL,
CONSTRAINT A_ID_PK PRIMARY KEY (A_ID));

CREATE TABLE PRICE(
PRICE_CODE VARCHAR(15) NOT NULL,
COST FLOAT,
CONSTRAINT PRICE_CODE_PK PRIMARY KEY (PRICE_CODE));

CREATE TABLE VIDEOS(
V_ID VARCHAR(15),
NAME_VID VARCHAR(30),
YEAR NUMBER,
VID_COST FLOAT NOT NULL,
VID_GENRE VARCHAR(15),
CONSTRAINT V_ID_PK PRIMARY KEY (V_ID));

CREATE TABLE RENTS(
CUST_EMAIL VARCHAR(30),
V_ID VARCHAR(15),
PRICE_CODE VARCHAR(15) NOT NULL,
FEES FLOAT NOT NULL,
LATE_FEES FLOAT NOT NULL,
RENT_DATE DATE,
RENT_DUE DATE,
RETURN_DATE DATE NOT NULL,
CONSTRAINT RENT_DATE_PK PRIMARY KEY (RENT_DATE),
CONSTRAINT RENT_CUST_EMAIL_FK FOREIGN KEY (CUST_EMAIL) REFERENCES CUSTOMER,
CONSTRAINT PRICE_CODE_FK FOREIGN KEY (PRICE_CODE) REFERENCES PRICE,
CONSTRAINT RENT_V_ID_FK FOREIGN KEY (V_ID) REFERENCES VIDEOS);

CREATE TABLE PERFORMS(
V_ID VARCHAR(15),
A_ID VARCHAR(15),
CONSTRAINT PERF_V_ID_FK FOREIGN KEY (V_ID) REFERENCES VIDEOS,
CONSTRAINT PERF_A_ID_FK FOREIGN KEY (A_ID) REFERENCES ACTOR);
