DROP TABLE BRANCH CASCADE CONSTRAINT;
DROP TABLE VEHICLE CASCADE CONSTRAINT;

CREATE TABLE BRANCH(
BRANCHID VARCHAR(5),
B_ADDRESS VARCHAR(55),
B_PHONE NUMBER(15),
B_MANAGER VARCHAR(10),
CONSTRAINT BRANCHID_PK PRIMARY KEY (BRANCHID));

CREATE TABLE VEHICLE(
VEHICLEID VARCHAR(5),
VHCL_MODEL VARCHAR(15),
VHCL_TYPE VARCHAR(15),
VHCL_RATE NUMBER(10),
BRANCHID VARCHAR(5),
CONSTRAINT VEHICLEID_PK PRIMARY KEY (VEHICLEID),
CONSTRAINT BRANCHID_VEHICLE_FK FOREIGN KEY (BRANCHID) REFERENCES BRANCH);